version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: sunday
      time: "13:15"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: sunday
      time: "13:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
