- id: codelimit
  name: codelimit
  description: "CodeLimit: Your Refactoring Alarm"
  verbose: true
  entry: codelimit check --quiet
  require_serial: true
  language: python
  types: [file, python]
