repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
# -   repo: https://github.com/getcodelimit/codelimit
    # rev: 8ca98dfaf3f8a2ccd1f5f856de85cb1d04d374a5
    # hooks:
    # - id: codelimit
