#!/usr/bin/env python3
from pathlib import Path
from typing import Optional

import typer

from codelimit.common.Report import Report
from codelimit.common.ReportSerializer import ReportSerializer
from codelimit.common.Scanner import Scanner
from codelimit.version import version, release_date


def scan_path(path: Optional[Path] = typer.Argument(Path('.'))):
    print('Code Limit')
    print(f'Version: {version}, released on: {release_date}')

    codebase = Scanner().scan(path)
    codebase.aggregate()
    print(f'Total lines of code: {codebase.total_loc()}')
    report = Report(codebase)
    print(f'Average length (LOC): {report.get_average()}')
    print(f'90th percentile: {report.ninetieth_percentile()}')
    report.display_risk_category_plot()
    with open('codelimit.json', 'w') as outfile:
        outfile.write(ReportSerializer(report).to_json())
    print('Output written to codelimit.json')


if __name__ == '__main__':
    typer.run(scan_path)
