name: 'main'
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 'Set up Poetry'
        uses: snok/install-poetry@v1
      - name: 'Install dependencies'
        run: poetry install --no-interaction --no-root
      - name: 'Run unit-tests'
        run: poetry run pytest --cov --cov-report=xml
      - name: 'Upload coverage reports to Codecov'
        uses: codecov/codecov-action@v3
      - name: 'Run Code Limit'
        uses: getcodelimit/codelimit-action@main
